### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by Hokwang** [eldada/jenkins-in-kubernetes#1]
Hello.

I am following your guide, but here's some questions.

If I need update jenkins or jenkins plugin version or add some plugin,
is it possible to have all job's history and log?
Please explain(add to readme file) this case.

and please consider more production env. friendly.
You can assume there's 3 servers, (I guess one is for jenkins master, others for jenkins agent)
how to use/set kubernetes and
how to build at agent server.
This is related https://github.com/eldada/jenkins-pipeline-kubernetes
I see below lines in Jenkinsfile.
`// In this example, all is built and run from the master
    agent { node { label 'master' } }
`

Thank you.

**Comment by eldada** [comment]
Hi @Hokwang ,
Thank you for the feedback.

Related to updates (Jenkins version, plugins etc.), the helm chart deploys Jenkins with a persistent storage (`storage.persistence.enabled=true`), which means any updates will keep all existing data under */var/jenkins_home*. This is relevant as long as Jenkins is deployed. Once you remove it, you will loose the PVC (default Kubernetes deployment behaviour). This is equivalent to docker's `-v /host/path:/var/jenkins_home`, which will keep your data across docker restarts and upgrades.

I added a note in https://github.com/eldada/jenkins-in-kubernetes#data-persistence

As for the use of Jenkins agents - I had plans on adding it later on. You are welcome to suggest and submit a pull request.
Remember this is an example only, and not really meant for production use. From README
```
IMPORTANT: This example is for demo and testing. It should not be used a production environment!
```

**Comment by Hokwang** [comment]
Thank you for your kind reply.
Now I am understand persistent storage.
And I will wait your next article about using jenkins with kubernetes for production environment.
I guess all workers in enterprise are looking forward to seeing your guide.
