### ISSUE TITLE
Run command in docker container not working

### ISSUE THREAD

**Issue by zd-dalibor** [eldada/jenkins-in-kubernetes#2]
For example if you want to run tests in container.

This is the simple example:
```groovy
pipeline {
    agent {
        docker { image 'node:7-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
```

you will get this error:
```
Jenkins seems to be running inside container f99772f7840e664d9095d48ddfdfa139e30fbf5cf9a98b5529c35b2e9ba9657d
but /var/jenkins_home/workspace/<jobname>_develop-W7GCLGJT2S2HKHL5KF3H7X7ZWQL4HBA4WDIAI5OALVZFBKPY76QA@2 could not be found among []
but /var/jenkins_home/workspace/jobname>_develop-W7GCLGJT2S2HKHL5KF3H7X7ZWQL4HBA4WDIAI5OALVZFBKPY76QA@2@tmp could not be found among []
...
sh: 1: cannot create /var/jenkins_home/workspace/<jobname>_develop-W7GCLGJT2S2HKHL5KF3H7X7ZWQL4HBA4WDIAI5OALVZFBKPY76QA@2@tmp/durable-3479ee34/jenkins-log.txt: Directory nonexistent
sh: 1: cannot create /var/jenkins_home/workspace/<jobname>_develop-W7GCLGJT2S2HKHL5KF3H7X7ZWQL4HBA4WDIAI5OALVZFBKPY76QA@2@tmp/durable-3479ee34/jenkins-result.txt.tmp: Directory nonexistent
mv: cannot stat '/var/jenkins_home/workspace/<jobname>_develop-W7GCLGJT2S2HKHL5KF3H7X7ZWQL4HBA4WDIAI5OALVZFBKPY76QA@2@tmp/durable-3479ee34/jenkins-result.txt.tmp': No such file or directory
process apparently never started in /var/jenkins_home/workspace/<jobname>_develop-W7GCLGJT2S2HKHL5KF3H7X7ZWQL4HBA4WDIAI5OALVZFBKPY76QA@2@tmp/durable-3479ee34
```

**Comment by eldada** [comment]
Hi @dalibor983. Thank for the feedback. I'll look into it.
You are also welcome to suggest a fix :-)

**Comment by zd-dalibor** [comment]
@eldada I think there is no fix for this.
The problem is, I think, that jenkins docker pipeline tries to mount job wokrspace in the created container bot this is not possible with DinD because jenkins using docker client to run docker commands on docker daemon outside of jenkins container. In that container job workspace does not exist.

The only solution is to using classic *sh* step in jenkins pipeline (```sh 'docker run --rm ...'```).
But I do not know how to get tests results after running tests in this way.

What I actually want to implement is CI/CD for my php containerized application and I want to run phpunite tests in application container but I must inform somehow jenkins job about test results to stop further steps in pipeline if tests failed.

**Comment by eldada** [comment]
The idea of the `sh 'docker run --rm...'` sounds like a good idea. Did you try mounting a tests results directory into it with `... -v jenkins_path:docker_path` and get the results in the job's workspace? Or this will fail for the same issue as suggested before?

**Comment by zd-dalibor** [comment]
@eldada Yes, it will fail for the same reason. Docker daemon will try to mount path from daemon container but path is actually in jenkins container.

**Comment by amcsi** [comment]
@dalibor983 how were you able to get the generated container name for running `docker run ... <container name>`?

**Comment by eldada** [comment]
@dalibor983 , @amcsi , I'm going to try and build a single image for Jenkins and dind, so it might help solve this issue. Will keep you posted.

**Comment by fvbcelltrak** [comment]
any update on this? with a single image for Jenkins and docker I get network errors; with dind I get "Directory nonexistent"

**Comment by eldada** [comment]
No. Sorry. No update. My previous attempts failed. Will try to get back to this in the coming weeks.

**Comment by buksy90** [comment]
Hello, have you found a solution?

**Comment by olivergg** [comment]
Could it be related : https://support.cloudbees.com/hc/en-us/articles/360029374071-Build-fails-with-process-apparently-never-started-error ?
(and btw, I've got the same issue with a JNLP agent installed with the method described in https://medium.com/hootsuite-engineering/building-docker-images-inside-kubernetes-42c6af855f25)

**Comment by zd-dalibor** [comment]
This k8s deployments starts pod with two containers. Something like this:
![image](https://user-images.githubusercontent.com/226822/63597959-e05a8e80-c5be-11e9-85d0-48105ff669fd.png)

When jenkins wants to start agent as docker container it calls cli docker client commands to run container. Docker client executes commands on docker daemon in the second DinD container over tcp. Agent container has mounded '/var/jenkins_home' directory but this directory does not exist in DinD container. I think if DinD container also mounts 'jenkins-home' volume agent will work.

Something like this:
![image](https://user-images.githubusercontent.com/226822/63598802-9a062f00-c5c0-11e9-9bda-f049d24d22fc.png)

**Comment by eldada** [comment]
Thanks @dalibor983 ! I will look into it. I was pre occupied with other things. I hope to test it in the coming days.

**Comment by eldada** [comment]
Seems #4 does fix this. Thanks @dalibor983 !
